theme="onedark"

[editor]
line-number="relative"
cursorline=true

[editor.cursor-shape]
insert="bar"
normal="block"

[editor.lsp]
display-inlay-hints=true

[editor.whitespace.render]
space="none"
tab="all"
newline="none"

[editor.whitespace.characters]
space = "·"
tab = "→"

[editor.indent-guides]
render=true
skip-levels = 1

[keys.normal]
space={c = {r = "rename_symbol", a = "code_action" }}
"K"="hover"

[keys.insert]
j = {k="normal_mode"}
"C-space"="completion"